### ISSUE TITLE
Error when the folder is already a git repo

### ISSUE THREAD

**Issue by bradbarrish** [mathieudutour/medium-to-own-blog#14]
```
? URL of the repository https://github.com/bradbarrish/bradbarrish-blog
⠋ Updating the project to use the repository URL
Error: Command failed: git init && git remote add origin https://github.com/bradbarrish/bradbarrish-blog && git add . && git commit -m "first commit :tada:"
fatal: remote origin already exists.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git init && git remote add origin ' +
    'https://github.com/bradbarrish/bradbarrish-blog && git add . && git ' +
    'commit -m "first commit :tada:"',
  stdout: 'Reinitialized existing Git repository in ' +
    '/Users/brad.barrish/bradbarrish-blog/.git/\n',
  stderr: 'fatal: remote origin already exists.\n'
}
```

**Comment by harshattray** [comment]
This shows up when the .git repo is already  initialised . In your case you can find it in  the path `/Users/brad.barrish/bradbarrish-blog/`.

**Comment by mathieudutour** [comment]
Did you already have a folder named `bradbarrish-blog` before?

**Comment by bradbarrish** [comment]
Nope, though I did run it once before with the same result.

**Comment by paramaggarwal** [comment]
Try running `git remote rm origin` in `/Users/brad.barrish/bradbarrish-blog/` and then re-run this script. I believe it failed due to some reason in the first pass and giving this error on the next run.

**Comment by mathieudutour** [comment]
We could perhaps check at the beginning if the folder already exists, and if so ask if we should continue. If we continue, then we can just ignore errors on `git init` and `git remote add`. And we should perhaps change the commit message to not be `First commit`.

**Comment by bradbarrish** [comment]
I ran `git remote rm origin` in `/Users/brad.barrish/bradbarrish-blog/` and then re-ran the script.

Results...

```
? URL of the repository https://github.com/bradbarrish/bradbarrish-blog
✖ Updating the project to use the repository URL

Error: Command failed: git init && git remote add origin https://github.com/bradbarrish/bradbarrish-blog && git add . && git commit -m "first commit :tada:"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'brad.barrish@bradbarrish.(none)')

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git init && git remote add origin ' +
    'https://github.com/bradbarrish/bradbarrish-blog && git add . && git ' +
    'commit -m "first commit :tada:"',
  stdout: 'Initialized empty Git repository in ' +
    '/Users/brad.barrish/bradbarrish-blog/bradbarrish-blog/.git/\n',
  stderr: '\n*** Please tell me who you are.\n\nRun\n\n  git config --global ' +
    'user.email "you@example.com"\n  git config --global user.name ' +
    `"Your Name"\n\nto set your account's default identity.\nOmit ` +
    '--global to set the identity only in this repository.\n\nfatal: ' +
    'unable to auto-detect email address (got ' +
    "'brad.barrish@bradbarrish.(none)')\n"
}
```

**Comment by mathieudutour** [comment]
ah so that was the first error probably. The error comes from the fact that you haven't really used git yet (haven't tested that scenario sorry).

So to fix, run
```
git config --global user.email "you@example.com"
```
then 
```
git config --global user.name "Your Name"
```

and then
```
git remote rm origin
```

and it should be all good. Sorry for the confusing error

**Comment by bradbarrish** [comment]
New machine, which explains that. Successfully got through that step, but the deploy failed. 

<details><summary>deploy logs</summary>
<pre>
2:56:39 PM: Build ready to start
2:56:45 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
2:56:45 PM: build-image tag: v3.3.2
2:56:45 PM: buildbot version: 75cd99f62ada9e21edea53208e8baf0eab85a045
2:56:45 PM: Fetching cached dependencies
2:56:45 PM: Failed to fetch cache, continuing with build
2:56:45 PM: Starting to prepare the repo for build
2:56:45 PM: No cached dependencies found. Cloning fresh repo
2:56:45 PM: git clone https://github.com/bradbarrish/bradbarrish-blog
2:56:46 PM: Preparing Git Reference refs/heads/master
2:56:47 PM: Found netlify.toml. Overriding site configuration
2:56:47 PM: Starting build script
2:56:47 PM: Installing dependencies
2:56:48 PM: Downloading and installing node v10.16.0...
2:56:49 PM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
2:56:49 PM: 
###
2:56:49 PM:                                     5.1%
2:56:49 PM: 
#################################
2:56:49 PM: ##############################           88.4%
2:56:49 PM: 
#######################################
2:56:49 PM: ################################# 100.0%
2:56:49 PM: Computing checksum with sha256sum
2:56:49 PM: Checksums matched!
2:56:52 PM: Now using node v10.16.0 (npm v6.9.0)
2:56:52 PM: Attempting ruby version 2.6.2, read from environment
2:56:54 PM: Using ruby version 2.6.2
2:56:54 PM: Using PHP version 5.6
2:56:54 PM: Started restoring cached node modules
2:56:54 PM: Finished restoring cached node modules
2:56:54 PM: Installing NPM modules using NPM version 6.9.0
2:56:57 PM: npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
2:57:00 PM: npm
2:57:00 PM: WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2:57:01 PM: npm WARN
2:57:01 PM:  deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
2:57:01 PM: npm WARN
2:57:01 PM:  deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
2:57:03 PM: npm WARN deprecated
2:57:03 PM:  hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2:57:03 PM: npm WARN deprecated
2:57:03 PM:  topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2:57:06 PM: npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
2:57:42 PM: > sharp@0.22.1 install /opt/build/repo/node_modules/sharp
2:57:42 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
2:57:42 PM: info
2:57:42 PM: sharp
2:57:42 PM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
2:57:44 PM: > pre-commit@1.2.2 install /opt/build/repo/node_modules/pre-commit
2:57:44 PM: > node install.js
2:57:45 PM: > core-js@2.6.9 postinstall /opt/build/repo/node_modules/core-js
2:57:45 PM: > node scripts/postinstall || echo "ignore"
2:57:45 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
2:57:45 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
2:57:45 PM: > https://opencollective.com/core-js 
2:57:45 PM: > https://www.patreon.com/zloirock 
2:57:45 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
2:57:45 PM: > core-js-pure@3.1.3 postinstall /opt/build/repo/node_modules/core-js-pure
2:57:45 PM: > node scripts/postinstall || echo "ignore"
2:57:45 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
2:57:45 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
2:57:45 PM: > https://opencollective.com/core-js 
2:57:45 PM: > https://www.patreon.com/zloirock 
2:57:45 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
2:57:45 PM: > spawn-sync@1.0.15 postinstall /opt/build/repo/node_modules/spawn-sync
2:57:45 PM: > node postinstall
2:57:45 PM: > gatsby-telemetry@1.0.11 postinstall /opt/build/repo/node_modules/gatsby-telemetry
2:57:45 PM: > node src/postinstall.js
2:57:46 PM: > cwebp-bin@5.1.0 postinstall /opt/build/repo/node_modules/cwebp-bin
2:57:46 PM: > node lib/install.js
2:57:46 PM:   ✔ cwebp pre-build test passed successfully
2:57:46 PM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
2:57:46 PM: > node lib/install.js
2:57:47 PM:   ✔ mozjpeg pre-build test passed successfully
2:57:47 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
2:57:47 PM: > node lib/install.js
2:57:47 PM:   ✔ pngquant pre-build test passed successfully
2:57:49 PM: npm notice
2:57:49 PM:  created a lockfile as package-lock.json. You should commit this file.
2:57:49 PM: npm WARN eslint-config-react-app@3.0.8 requires a peer of babel-eslint@9.x but none is installed. You must install peer dependencies yourself.
2:57:49 PM: npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
2:57:49 PM: npm WARN
2:57:49 PM:  optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
2:57:49 PM: npm WARN
2:57:49 PM: notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:57:49 PM: added 2026 packages from 1118 contributors and audited 30299 packages in 54.316s
2:57:49 PM: found 0 vulnerabilities
2:57:49 PM: NPM modules installed
2:57:50 PM: Started restoring cached go cache
2:57:50 PM: Finished restoring cached go cache
2:57:50 PM: unset GOOS;
2:57:50 PM: unset GOARCH;
2:57:50 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
2:57:50 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
2:57:50 PM: go version >&2;
2:57:50 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
2:57:50 PM: go version go1.12 linux/amd64
2:57:50 PM: Installing missing commands
2:57:50 PM: Verify run directory
2:57:50 PM: Executing user command: gatsby build
2:57:52 PM: success open and validate gatsby-configs — 0.010 s
2:57:53 PM: success load plugins — 0.815 s
2:57:53 PM: success onPreInit — 0.005 s
2:57:53 PM: success delete html and css files from previous builds — 0.006 s
2:57:53 PM: success initialize cache — 0.007 s
2:57:53 PM: success copy gatsby files — 0.019 s
2:57:53 PM: success onPreBootstrap — 0.012 s
2:57:54 PM: error Plugin gatsby-mdx returned an error
2:57:55 PM: 
2:57:55 PM:   SyntaxError: unknown: Expected corresponding JSX closing tag for <p> (8:567)
2:57:55 PM:      6 |       components={components}>
2:57:55 PM:      7 | <p><h1>{`After More Than A Decade, I’m Done With Evernote`}</h1></p>
2:57:55 PM:   >  8 | <p><p>{`This week I finally was able to check a todo item off my list t  hat I had been procrastinating for over a month. I migrated tens of thousands   of mostly PDF documents out of Evernote and overhauled my personal information   management system. If you’re curious how I used to do things, <a href=”`}<a p  arentName="p" {...{"href":"https://medium.com/@bradbarrish/evernote-is-at-the-  center-of-my-digital-life-bcbca3df8804%22%3EI"}}>{`https://medium.com/@bradbar  rish/evernote-is-at-the-center-of-my-digital-life-bcbca3df8804">I`}</a>{` wrot  e that up a few years back`}</a>{`. I had so much stuff in Evernote and had be  en using it for well over a decade, but it was time to revisit how I was stori  ng and using digital stuff. It’s worth mentioning, that I didn’t take many act  ual notes in Evernote and as time went on I couldn’t stand using it for that p  urpose. The app had really become bloated and I didn’t enjoy writing in it. Th  e kicker, at least for me, was also that it didn’t natively support `}<a href=  ”https://en.m.wikipedia.org/wiki/Markdown”>{`Markdown`}</a>{`. The other thing   I used it for was to archiving everything I posted and favorited online. This   was all done through a service called `}<a href=”https://ifttt.com”>{`IFTTT`}  </a>{` (If This Then That), about which I could (and probably should) write so  mething up as well. Another time, but I’ll touch on what I did with all those   notes a little further down.`}</p></p>
2:57:55 PM:        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^
2:57:55 PM:      9 | <p><p>{`If Evernote was the center of my digital life, my trusty`}<a hr  ef=”https://amzn.to/2znOaIZ”>{`Fujitsu ScanSnap`}</a>{` was the key that enabl  ed it. I just purchased a new one this year after the original one I bought ba  ck in 2010 stopped working. I cannot recommend it enough. I scan everything —   mail, receipts, bills, warranties, documentation, but not photos. I use the sc  anner for the vast majority of it but also use `}<a href=”https://scanbot.io/e  n/index.html”>{`Scanbot Pro`}</a>{` on my iPhone or iPad. For what its worth,   I use `}<a href=”https://www.scancafe.com”>{`Scan Cafe`}</a>{` to scan my phys  ical photos.`}</p></p>
2:57:55 PM:     10 | <p><p>{`One of the main reasons I started using Evernote to begin with   was for its incredible optical character recognition (OCR) capabilities, which   is no longer a unique feature. Today, if you want to search through indexed P  DFs, Google Drive and macOS both have this feature, which in my experience wor  ks just as well, if not better. What OCR allows me to do is search the text in  side a PDF document. For example, if I want to gather all of my doctor bills t  o review , I simply search for my doctor’s name (or some other unique identifi  er that appears on all of his bills) and in a matter of a second, they’re gath  ered and ready for review. I cannot overstate what a tremendous timesaver bein  g completely paperless is. It takes up no space, is completely affordable and   allows you to be a digital hoarder with no shame whatsoever.`}</p></p>
2:57:55 PM:     11 | <p><p>{`Evernote can export notes in their native format (.enex) or in   HTML. Thankfully many note-taking apps can easily import Evernote files. You c  an do it one-by-one by simply dragging a note from Evernote to a folder on you  r computer (I did this all on my MacBook Pro, not on my iPad) or select multip  le notes and drag them together. You can also select a single or multiple note  s and export just the file attachments. This was particularly helpful to me si  nce, again, most of what I had in Evernote were PDFs. I already pay for G Suit  e so I settled on using Google Drive to store PDFs. G Suite is Google’s paid s  ervice (I pay $5/month) and differs form their free services you probably use.   The great thing about G Suite, aside from being able to use my own domain, is   the lack of advertising and data collection by Google. They have no plans to   change this in the future, which is great. According to them, they do not coll  ect, scan or use data in G Suite Core Services for advertising purposes. While   I don’t feel awesome about Google from a privacy standpoint, but I’m willing   to give a little to get the convenience and interoperability with devices and   other services I use. Once I moved all of my documents to Google Drive, I crea  ted a single folder on my iCloud Drive and dropped them all in there for redun  dancy. I also plan to back them up on a physical drive. `}</p></p>/opt/build/r  epo/content/lessh1greaterAfter-More-Than-A-Decade-I'm-Done-With-Evernotelessh1  greater/index.md: unknown: Expected corresponding JSX closing tag for <p> (8:5  67)
2:57:55 PM:      6 |       components={components}>
2:57:55 PM:      7 | <p><h1>{`After More Than A Decade, I’m Done With Evernote`}</h1></p>
2:57:55 PM:   >  8 | <p><p>{`This week I finally was able to check a todo item off my list t  hat I had been procrastinating for over a month. I migrated tens of thousands   of mostly PDF documents out of Evernote and overhauled my personal information   management system. If you’re curious how I used to do things, <a href=”`}<a p  arentName="p" {...{"href":"https://medium.com/@bradbarrish/evernote-is-at-the-  center-of-my-digital-life-bcbca3df8804%22%3EI"}}>{`https://medium.com/@bradbar  rish/evernote-is-at-the-center-of-my-digital-life-bcbca3df8804">I`}</a>{` wrot  e that up a few years back`}</a>{`. I had so much stuff in Evernote and had be  en using it for well over a decade, but it was time to revisit how I was stori  ng and using digital stuff. It’s worth mentioning, that I didn’t take many act  ual notes in Evernote and as time went on I couldn’t stand using it for that p  urpose. The app had really become bloated and I didn’t enjoy writing in it. Th  e kicker, at least for me, was also that it didn’t natively support `}<a href=  ”https://en.m.wikipedia.org/wiki/Markdown”>{`Markdown`}</a>{`. The other thing   I used it for was to archiving everything I posted and favorited online. This   was all done through a service called `}<a href=”https://ifttt.com”>{`IFTTT`}  </a>{` (If This Then That), about which I could (and probably should) write so  mething up as well. Another time, but I’ll touch on what I did with all those   notes a little further down.`}</p></p>
2:57:55 PM:        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^
2:57:55 PM:      9 | <p><p>{`If Evernote was the center of my digital life, my trusty`}<a hr  ef=”https://amzn.to/2znOaIZ”>{`Fujitsu ScanSnap`}</a>{` was the key that enabl  ed it. I just purchased a new one this year after the original one I bought ba  ck in 2010 stopped working. I cannot recommend it enough. I scan everything —   mail, receipts, bills, warranties, documentation, but not photos. I use the sc  anner for the vast majority of it but also use `}<a href=”https://scanbot.io/e  n/index.html”>{`Scanbot Pro`}</a>{` on my iPhone or iPad. For what its worth,   I use `}<a href=”https://www.scancafe.com”>{`Scan Cafe`}</a>{` to scan my phys  ical photos.`}</p></p>
2:57:55 PM:     10 | <p><p>{`One of the main reasons I started using Evernote to begin with   was for its incredible optical character recognition (OCR) capabilities, which   is no longer a unique feature. Today, if you want to search through indexed P  DFs, Google Drive and macOS both have this feature, which in my experience wor  ks just as well, if not better. What OCR allows me to do is search the text in  side a PDF document. For example, if I want to gather all of my doctor bills t  o review , I simply search for my doctor’s name (or some other unique identifi  er that appears on all of his bills) and in a matter of a second, they’re gath  ered and ready for review. I cannot overstate what a tremendous timesaver bein  g completely paperless is. It takes up no space, is completely affordable and   allows you to be a digital hoarder with no shame whatsoever.`}</p></p>
2:57:55 PM:     11 | <p><p>{`Evernote can export notes in their native format (.enex) or in   HTML. Thankfully many note-taking apps can easily import Evernote files. You c  an do it one-by-one by simply dragging a note from Evernote to a folder on you  r computer (I did this all on my MacBook Pro, not on my iPad) or select multip  le notes and drag them together. You can also select a single or multiple note  s and export just the file attachments. This was particularly helpful to me si  nce, again, most of what I had in Evernote were PDFs. I already pay for G Suit  e so I settled on using Google Drive to store PDFs. G Suite is Google’s paid s  ervice (I pay $5/month) and differs form their free services you probably use.   The great thing about G Suite, aside from being able to use my own domain, is   the lack of advertising and data collection by Google. They have no plans to   change this in the future, which is great. According to them, they do not coll  ect, scan or use data in G Suite Core Services for advertising purposes. While   I don’t feel awesome about Google from a privacy standpoint, but I’m willing   to give a little to get the convenience and interoperability with devices and   other services I use. Once I moved all of my documents to Google Drive, I crea  ted a single folder on my iCloud Drive and dropped them all in there for redun  dancy. I also plan to back them up on a physical drive. `}</p></p>
2:57:55 PM:   
2:57:55 PM:   - index.js:6344 Object.raise
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:6344:17
2:57:55 PM:   
2:57:55 PM:   - index.js:3561 Object.jsxParseElementAt
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:3561:16
2:57:55 PM:   
2:57:55 PM:   - index.js:3529 Object.jsxParseElementAt
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:3529:32
2:57:55 PM:   
2:57:55 PM:   - index.js:3529 Object.jsxParseElementAt
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:3529:32
2:57:55 PM:   
2:57:55 PM:   - index.js:3587 Object.jsxParseElement
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:3587:17
2:57:55 PM:   
2:57:55 PM:   - index.js:3594 Object.parseExprAtom
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:3594:19
2:57:55 PM:   
2:57:55 PM:   - index.js:8413 Object.parseExprSubscripts
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:8413:23
2:57:55 PM:   
2:57:55 PM:   - index.js:8393 Object.parseMaybeUnary
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:8393:21
2:57:55 PM:   
2:57:55 PM:   - index.js:8280 Object.parseExprOps
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:8280:23
2:57:55 PM:   
2:57:55 PM:   - index.js:8253 Object.parseMaybeConditional
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:8253:23
2:57:55 PM:   
2:57:55 PM:   - index.js:8200 Object.parseMaybeAssign
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:8200:21
2:57:55 PM:   
2:57:55 PM:   - index.js:8963 Object.parseParenAndDistinguishExpression
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:8963:28
2:57:55 PM:   
2:57:55 PM:   - index.js:8760 Object.parseExprAtom
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:8760:21
2:57:55 PM:   
2:57:55 PM:   - index.js:3599 Object.parseExprAtom
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:3599:20
2:57:55 PM:   
2:57:55 PM:   - index.js:8413 Object.parseExprSubscripts
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:8413:23
2:57:55 PM:   
2:57:55 PM:   - index.js:8393 Object.parseMaybeUnary
2:57:55 PM:     [repo]/[@babel]/parser/lib/index.js:8393:21
2:57:55 PM:   
2:57:55 PM: 
2:57:55 PM: Skipping functions preparation step: no functions directory set
2:57:55 PM: Caching artifacts
2:57:55 PM: Started saving node modules
2:57:55 PM: Finished saving node modules
2:57:55 PM: Started saving pip cache
2:57:55 PM: Finished saving pip cache
2:57:55 PM: Started saving emacs cask dependencies
2:57:55 PM: Finished saving emacs cask dependencies
2:57:55 PM: Started saving maven dependencies
2:57:55 PM: Finished saving maven dependencies
2:57:55 PM: Started saving boot dependencies
2:57:55 PM: Finished saving boot dependencies
2:57:55 PM: Started saving go dependencies
2:57:55 PM: Finished saving go dependencies
2:57:57 PM: Error running command: Build script returned non-zero exit code: 1
2:57:57 PM: Failing build: Failed to build site
2:57:57 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
2:57:57 PM: Finished processing build request in 1m12.487579506s
2:57:57 PM: Shutting down logging, 0 messages pending
</pre>
</details>

**Comment by mathieudutour** [comment]
So I think that a different issue. ~~It's because of a weird white space in the title and in the middle of the article~~ ~~It's because of an italic link (`[_label_](url)`)~~ It's because there is a draft with some links that aren't transformed to markdown (eg. still `<a href=”https://bear.app”>Bear</a>`), and in mdx, `//` is a comment so it skips the end of the line which contain the closing tag. I'll try to see what's the issue but it's unrelated.

**Comment by bradbarrish** [comment]
Got it. Thanks for all the help and patience. The site now seems to be working and looks great. 🙏

**Comment by shveikus** [comment]
close this issue

**Comment by mathieudutour** [comment]
No let's keep it open and do this:

- check at the beginning if the folder already exists, and if so ask if we should continue
- If we continue, then we can just ignore errors on git init and git remote add
- we should also perhaps change the commit message to not be First commit.

**Comment by jsj14** [comment]
> Got it. Thanks for all the help and patience. The site now seems to be working and looks great. 🙏

@bradbarrish So did you remove the drafts from your medium blog? 
(i tried creating a new repo, and redoing it all, still getting the same error)

**Comment by bradbarrish** [comment]
I believe so, yes. Will confirm and let you know.

**Comment by jsj14** [comment]
So the deploy to Netlify breaks when it gets empty date or any other field. The docs say that we can keep it empty for drafts until we publish it. 
`failed during stage 'building site': Build script returned non-zero exit code: 1
12:31:40 AM:         categories
12:31:40 AM:         date(formatString: "MMMM DD, YYYY")`

**Comment by mathieudutour** [comment]
Ah interesting. Could you open another issue? It’s a bit different from this one
