### ISSUE TITLE
Cannot read property 'textContent' of null

### ISSUE THREAD

**Issue by paramaggarwal** [mathieudutour/medium-to-own-blog#3]
**Describe the bug**

```
TypeError: Cannot read property 'textContent' of null
    at module.exports.getMarkdownFromPost (/Users/param/.npm/_npx/16523/lib/node_modules/medium-to-own-blog/generate-md.js:182:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Screenshots**
<img width="801" alt="Screenshot 2019-05-31 at 11 39 16 PM" src="https://user-images.githubusercontent.com/543981/58725647-4c34bd00-83fd-11e9-916e-fab3720f9e93.png">

**Comment by paramaggarwal** [comment]
This was fixed in 614426785442927ea26312a35bf347d81a5cc0d5.
